import Header from '@/site/components/Sections/Header';
import Hello from '@/site/components/Sections/Hello';
import MyProjects from '@/site/components/Sections/Projects';
import Resume from '@/site/components/Sections/Resume';
import Testimonials from '@/site/components/Sections/Testimonials';
import dynamic from 'next/dynamic';
import { Element } from 'react-scroll';

const Head = dynamic(() => import('next/head'));
const Layout = dynamic(() => import('./../site/components/Layout'));

export default function Home() {

  return (
    <>
      <Head>
        <title>Alphadevking | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Layout navbar footer>

        <Element name='/'>
          <Header />
        </Element>

        <Element name='' className='pt-16 md:pt-24'>
          <Hello />
        </Element>

        <Element name='resume' className='pt-16 md:pt-24'>
          <Resume />
        </Element>

        <Element name='portfolio' className='pt-16 md:pt-24'>
          <MyProjects />
        </Element>

        <Element name='testimonial' className='pt-16 md:pt-24'>
          <Testimonials/>
        </Element>

      </Layout>
    </>
  )
}
